mods = [
    { descriptor = "mods/mod_canvas/mod.toml" },
    { descriptor = "mods/mod_block/mod.toml" },
    { descriptor = "mods/mod_physics/mod.toml" },
    { descriptor = "mods/mod_player/mod.toml" },
    { descriptor = "mods/mod_car/mod.toml" },
    { descriptor = "mods/mod_game_loader/mod.toml" }
]
